from pathlib import Path

### DIRECTORIES

ROOT = Path(__file__).resolve().parents[1]

# configs
CONFIG_DIR = ROOT / 'configuration'
DATA_DICTIONARY_FILE_PATH = CONFIG_DIR / 'data_dictionary.json'
WINDOW_CONFIG_FILE_PATH = CONFIG_DIR / 'window_config.yml'

# drift characterization
DRIFT_CHARACTERIZATION_DIR = ROOT / 'concept-drift-characterization'
DRIFT_CHARACTERIZATION_TEMP_INPUT_DIR = DRIFT_CHARACTERIZATION_DIR / 'input'
DRIFT_CHARACTERIZATION_TEMP_OUTPUT_DIR = DRIFT_CHARACTERIZATION_DIR / 'output'
DRIFT_CHARACTERIZATION_SCRIPT = Path("main.py") # relative to DRIFT_CHARACTERIZATION_DIR

# results
RESULTS_DIR = ROOT / 'results'
DRIFT_CHARACTERIZATION_RESULTS_DIR = RESULTS_DIR / 'drift_detection'
COMPLEXITY_RESULTS_DIR = RESULTS_DIR / 'complexity_assessment'
COMPLEXITY_PLOTS_DIR = COMPLEXITY_RESULTS_DIR
COMBINED_RESULTS_DIR = RESULTS_DIR / 'combined_results'
COMBINED_RESULTS_TABLE_DIR = COMBINED_RESULTS_DIR / 'tables'
COMBINED_RESULTS_BOXPLOT_DIR = COMBINED_RESULTS_DIR / 'boxplots'
CORRELATION_RESULTS_DIR = RESULTS_DIR / 'correlations'

### CONSTANT CONFIGURATIONS
DEFAULT_CHANGE_POINT_PARAMETER_SETTING = 'processGraphsPDefaultWDefault'
DEFAULT_COMPLEXITY_WINDOW_SETTING = 'cp_default'
DEFAULT_CORRELATION_ANLAYSIS_NAME = 'default'

